import QuoteCard from "@/app/component/QuoteCard";
import Link from "next/link";

export const metadata = {
    title: "Quotes",
    description: "Generated by create next app",
  };


  export const revalidate = 10

const Quotes = async () => {
    let quotes = await fetch("https://dummyjson.com/quotes/random")
    quotes = await quotes.json();    
    return (
                <div className="p-10">
                    <h1 className="font-bold text-3xl text-center">Quotes</h1>
                    {/* {
                        quotes.quotes.map((data) => (
                        
                       <Link key={data.id} href={`/quotes/${data.id}`}>  */}
                       <QuoteCard author={quotes.author} quote={quotes.quote}/>
                       {/* </Link>  */}

                        
                    {/* ))} */}
                </div>
    );
};

export default Quotes;


// export default async function Quotes() {
//     return (
//         <div className="p-10">
//             <h1 className="font-bold text-3xl text-center">Quotes</h1>
//         </div>
//     )
// } 